version: '3.9'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      # - ./mlruns:/mlflow/mlruns
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: >
      mlflow server
      --host 0.0.0.0
# --default-artifact-root http://localhost:5000/mlflow/mlruns
      # --backend-store-uri sqlite:///mlflow.db
      # --default-artifact-root /mlruns
