version: '3.8'

services:
  web:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    ports:
      - "8001:8001"
    volumes:
      - ./api/app:/app
      - ./api/prisma:/app/prisma
      - ./api/.env:/app/.env
    depends_on:
      - redis
    environment:
      - ENV_FILE=.env
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend

networks:
  backend:
    driver: bridge
