# Use an official base image (e.g., Python 3.9)
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on (if applicable)
EXPOSE 8000



# Define the command to run the application
CMD ["python", "app/main.py"]